/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carparko;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nilay
 */
public class AddRecord extends javax.swing.JFrame {

    private int rid;
    Homepage hm = new Homepage();
    private int v_type = 1;
    private ArrayList v_vid;
    /**
     * Creates new form AddRecord
     */
    public AddRecord(Homepage h) {
        initComponents();
        super.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-parking-48.png")).getImage()); // NOI18N
        hm = h;
        rid = hm.get_r_length()+1;
        v_vid = hm.get_r_vid();
        record_id.setText(Integer.toString(rid));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        record_id_label = new javax.swing.JLabel();
        record_id = new javax.swing.JLabel();
        vid_label = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        v_type_label = new javax.swing.JLabel();
        v_type_car = new javax.swing.JRadioButton();
        v_type_truck = new javax.swing.JRadioButton();
        v_size_label = new javax.swing.JLabel();
        v_size = new javax.swing.JTextField();
        v_time = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Record - CarParko");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("CarParko");

        record_id_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        record_id_label.setText("Record ID:");

        record_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        vid_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vid_label.setText("Vehicle ID:");

        vid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });

        v_type_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_type_label.setText("Vehicle Type:");

        v_type_car.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_type_car.setText("Car");
        v_type_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_type_carActionPerformed(evt);
            }
        });

        v_type_truck.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_type_truck.setText("Truck");
        v_type_truck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_type_truckActionPerformed(evt);
            }
        });

        v_size_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_size_label.setText("Vehicle Size:");

        v_size.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_sizeActionPerformed(evt);
            }
        });

        v_time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        v_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_timeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Duration:");

        submit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v_size_label)
                                    .addComponent(v_type_label)
                                    .addComponent(vid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(record_id_label)
                                    .addComponent(jLabel2))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v_size)
                                    .addComponent(record_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vid)
                                    .addComponent(v_time)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(v_type_car)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                        .addComponent(v_type_truck)
                                        .addGap(70, 70, 70))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(record_id_label)
                    .addComponent(record_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_type_car)
                    .addComponent(v_type_truck)
                    .addComponent(v_type_label))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_size_label)
                    .addComponent(v_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
        submitActionPerformed(evt);
    }//GEN-LAST:event_vidActionPerformed

    private void v_type_truckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_type_truckActionPerformed
        // TODO add your handling code here:
        if (v_type_truck.isSelected()) {
            v_type_car.setSelected(false);
            v_type = 2;
        }
    }//GEN-LAST:event_v_type_truckActionPerformed

    private void v_type_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_type_carActionPerformed
        // TODO add your handling code here:
        if (v_type_car.isSelected()) {
            v_type_truck.setSelected(false);
            v_type = 1;
        }
    }//GEN-LAST:event_v_type_carActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if (!isInt(vid.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Vehicle ID!", "CarParko", JOptionPane.ERROR_MESSAGE);
        }
        else if (v_vid.contains(Integer.parseInt(vid.getText())) == true) {
            JOptionPane.showMessageDialog(this, "Vehicle ID already exists!", "CarParko", JOptionPane.ERROR_MESSAGE);
        }
        else if (!v_type_car.isSelected() && !v_type_truck.isSelected()) {
            JOptionPane.showMessageDialog(this, "Invalid Vehicle Type!", "CarParko", JOptionPane.ERROR_MESSAGE);
        }
        else if (!isInt(v_size.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Vehicle Size!", "CarParko", JOptionPane.ERROR_MESSAGE);
        }
        else if (!isInt(v_time.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Duration!", "CarParko", JOptionPane.ERROR_MESSAGE);
        }
        else {
            hm.addRecord(Integer.parseInt(vid.getText()), v_type, Integer.parseInt(v_size.getText()), Integer.parseInt(v_time.getText()));
            JOptionPane.showMessageDialog(this, "Record Successfully Added.", "CarParko", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void v_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_sizeActionPerformed
        // TODO add your handling code here:
        submitActionPerformed(evt);
    }//GEN-LAST:event_v_sizeActionPerformed

    private void v_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_timeActionPerformed
        // TODO add your handling code here:
        submitActionPerformed(evt);
    }//GEN-LAST:event_v_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddRecord().setVisible(true);
//            }
//        });
    }
    
    public boolean isInt(String s) {
        boolean isValidInt = false;
        
        try {
            Integer.parseInt(s);
            isValidInt = true;
        }
        catch (NumberFormatException e) {
            // exception code goes here
        }
        
        return isValidInt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel record_id;
    private javax.swing.JLabel record_id_label;
    private javax.swing.JButton submit;
    private javax.swing.JTextField v_size;
    private javax.swing.JLabel v_size_label;
    private javax.swing.JTextField v_time;
    private javax.swing.JRadioButton v_type_car;
    private javax.swing.JLabel v_type_label;
    private javax.swing.JRadioButton v_type_truck;
    private javax.swing.JTextField vid;
    private javax.swing.JLabel vid_label;
    // End of variables declaration//GEN-END:variables
}
