/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carparko;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nilay
 */
public class Homepage extends javax.swing.JFrame {
    
    //parking space values
    private int[] p_block = new int[10];
    private int[] p_block_bool = new int[10]; // -1 means block is empty
    private int[] p_vid = new int[10];
    private int[] p_type = new int[10];
    private int[] p_size = new int[10];
    private int[] p_time = new int[10];
    private long[] p_tlimit = new long[10];
    private long[] p_rmv_notified = new long[10];
    private final long RMV_NOTIFY_TIME = 30000; //30 s

    //Record new vehicle's entry
    private ArrayList r_vid = new ArrayList();
    private ArrayList r_type = new ArrayList();
    private ArrayList r_size = new ArrayList();
    private ArrayList r_time = new ArrayList();
    
    javax.swing.JPanel w_subpanel; // to store the waiting subpanel to be deleted
    boolean w_subpanel_bool = false;
    int w_subpanel_vid = -1;

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        super.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-parking-48.png")).getImage()); // NOI18N
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Arrays.fill(p_block, 0);
        Arrays.fill(p_block_bool, -1);
        Arrays.fill(p_rmv_notified, 0);
        initParking();
    }
    
    public Homepage(Homepage h) {
        initComponents();
        Homepage hm = new Homepage();
        hm = h;
        super.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-parking-48.png")).getImage()); // NOI18N
//        hm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Arrays.fill(p_block, 0);
        Arrays.fill(p_block_bool, -1);
        Arrays.fill(p_rmv_notified, 0);
        initParking();
    }
    
    public Homepage(int[] blocks) {
        initComponents();
        super.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-parking-48.png")).getImage()); // NOI18N
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        p_block = Arrays.copyOf(blocks, blocks.length);
        Arrays.fill(p_block_bool, -1);
        Arrays.fill(p_rmv_notified, 0);
        initParking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        action_panel = new javax.swing.JPanel();
        action_jPanel1 = new javax.swing.JPanel();
        action_jPanel1_jLabel1 = new javax.swing.JLabel();
        action_jPanel2 = new javax.swing.JPanel();
        action_jPanel2_jLabel1 = new javax.swing.JLabel();
        action_jPanel3 = new javax.swing.JPanel();
        action_jPanel3_jLabel1 = new javax.swing.JLabel();
        waiting_scrollpanel = new javax.swing.JScrollPane();
        waiting_child_panel = new javax.swing.JPanel();
        waiting_jPanel1 = new javax.swing.JPanel();
        waiting_jPanel1_jLabel1 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel2 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel3 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel4 = new javax.swing.JLabel();
        parking_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        parking_scrollpanel = new javax.swing.JScrollPane();
        parking_child_panel = new javax.swing.JPanel();
        parking_jPanel1 = new javax.swing.JPanel();
        parking_jPanel1_jLabel4 = new javax.swing.JLabel();
        parking_jPanel1_jLabel2 = new javax.swing.JLabel();
        parking_jPanel1_jLabel3 = new javax.swing.JLabel();
        parking_jPanel1_jLabel1 = new javax.swing.JLabel();
        parking_jPanel1_jLabel5 = new javax.swing.JLabel();
        parking_jPanel1_jLabel6 = new javax.swing.JLabel();
        parking_jPanel2 = new javax.swing.JPanel();
        parking_jPanel2_jLabel1 = new javax.swing.JLabel();
        parking_jPanel2_jLabel4 = new javax.swing.JLabel();
        parking_jPanel2_jLabel5 = new javax.swing.JLabel();
        parking_jPanel2_jLabel2 = new javax.swing.JLabel();
        parking_jPanel2_jLabel3 = new javax.swing.JLabel();
        parking_jPanel2_jLabel6 = new javax.swing.JLabel();
        parking_jPanel3 = new javax.swing.JPanel();
        parking_jPanel3_jLabel1 = new javax.swing.JLabel();
        parking_jPanel3_jLabel4 = new javax.swing.JLabel();
        parking_jPanel3_jLabel5 = new javax.swing.JLabel();
        parking_jPanel3_jLabel2 = new javax.swing.JLabel();
        parking_jPanel3_jLabel3 = new javax.swing.JLabel();
        parking_jPanel3_jLabel6 = new javax.swing.JLabel();
        parking_jPanel4 = new javax.swing.JPanel();
        parking_jPanel4_jLabel1 = new javax.swing.JLabel();
        parking_jPanel4_jLabel4 = new javax.swing.JLabel();
        parking_jPanel4_jLabel5 = new javax.swing.JLabel();
        parking_jPanel4_jLabel2 = new javax.swing.JLabel();
        parking_jPanel4_jLabel3 = new javax.swing.JLabel();
        parking_jPanel4_jLabel6 = new javax.swing.JLabel();
        parking_jPanel5 = new javax.swing.JPanel();
        parking_jPanel5_jLabel1 = new javax.swing.JLabel();
        parking_jPanel5_jLabel4 = new javax.swing.JLabel();
        parking_jPanel5_jLabel5 = new javax.swing.JLabel();
        parking_jPanel5_jLabel2 = new javax.swing.JLabel();
        parking_jPanel5_jLabel3 = new javax.swing.JLabel();
        parking_jPanel5_jLabel6 = new javax.swing.JLabel();
        parking_jPanel6 = new javax.swing.JPanel();
        parking_jPanel6_jLabel1 = new javax.swing.JLabel();
        parking_jPanel6_jLabel4 = new javax.swing.JLabel();
        parking_jPanel6_jLabel5 = new javax.swing.JLabel();
        parking_jPanel6_jLabel2 = new javax.swing.JLabel();
        parking_jPanel6_jLabel3 = new javax.swing.JLabel();
        parking_jPanel6_jLabel6 = new javax.swing.JLabel();
        parking_jPanel7 = new javax.swing.JPanel();
        parking_jPanel7_jLabel1 = new javax.swing.JLabel();
        parking_jPanel7_jLabel4 = new javax.swing.JLabel();
        parking_jPanel7_jLabel5 = new javax.swing.JLabel();
        parking_jPanel7_jLabel2 = new javax.swing.JLabel();
        parking_jPanel7_jLabel3 = new javax.swing.JLabel();
        parking_jPanel7_jLabel6 = new javax.swing.JLabel();
        parking_jPanel8 = new javax.swing.JPanel();
        parking_jPanel8_jLabel1 = new javax.swing.JLabel();
        parking_jPanel8_jLabel4 = new javax.swing.JLabel();
        parking_jPanel8_jLabel5 = new javax.swing.JLabel();
        parking_jPanel8_jLabel2 = new javax.swing.JLabel();
        parking_jPanel8_jLabel3 = new javax.swing.JLabel();
        parking_jPanel8_jLabel6 = new javax.swing.JLabel();
        parking_jPanel9 = new javax.swing.JPanel();
        parking_jPanel9_jLabel1 = new javax.swing.JLabel();
        parking_jPanel9_jLabel4 = new javax.swing.JLabel();
        parking_jPanel9_jLabel5 = new javax.swing.JLabel();
        parking_jPanel9_jLabel2 = new javax.swing.JLabel();
        parking_jPanel9_jLabel3 = new javax.swing.JLabel();
        parking_jPanel9_jLabel6 = new javax.swing.JLabel();
        parking_jPanel10 = new javax.swing.JPanel();
        parking_jPanel10_jLabel1 = new javax.swing.JLabel();
        parking_jPanel10_jLabel4 = new javax.swing.JLabel();
        parking_jPanel10_jLabel5 = new javax.swing.JLabel();
        parking_jPanel10_jLabel2 = new javax.swing.JLabel();
        parking_jPanel10_jLabel3 = new javax.swing.JLabel();
        parking_jPanel10_jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarParko");

        action_jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action_jPanel1MouseClicked(evt);
            }
        });

        action_jPanel1_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-plus-48.png"))); // NOI18N

        javax.swing.GroupLayout action_jPanel1Layout = new javax.swing.GroupLayout(action_jPanel1);
        action_jPanel1.setLayout(action_jPanel1Layout);
        action_jPanel1Layout.setHorizontalGroup(
            action_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action_jPanel1_jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        action_jPanel1Layout.setVerticalGroup(
            action_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action_jPanel1_jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        action_jPanel2_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-remove-property-48.png"))); // NOI18N
        action_jPanel2_jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action_jPanel2_jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout action_jPanel2Layout = new javax.swing.GroupLayout(action_jPanel2);
        action_jPanel2.setLayout(action_jPanel2Layout);
        action_jPanel2Layout.setHorizontalGroup(
            action_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_jPanel2_jLabel1)
                .addContainerGap())
        );
        action_jPanel2Layout.setVerticalGroup(
            action_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_jPanel2_jLabel1)
                .addContainerGap())
        );

        action_jPanel3_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-property-script-48.png"))); // NOI18N
        action_jPanel3_jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action_jPanel3_jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout action_jPanel3Layout = new javax.swing.GroupLayout(action_jPanel3);
        action_jPanel3.setLayout(action_jPanel3Layout);
        action_jPanel3Layout.setHorizontalGroup(
            action_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_jPanel3_jLabel1)
                .addContainerGap())
        );
        action_jPanel3Layout.setVerticalGroup(
            action_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_jPanel3_jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout action_panelLayout = new javax.swing.GroupLayout(action_panel);
        action_panel.setLayout(action_panelLayout);
        action_panelLayout.setHorizontalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addComponent(action_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(action_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(action_jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        action_panelLayout.setVerticalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action_jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action_jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action_jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        waiting_jPanel1_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        waiting_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        waiting_jPanel1_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        waiting_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout waiting_jPanel1Layout = new javax.swing.GroupLayout(waiting_jPanel1);
        waiting_jPanel1.setLayout(waiting_jPanel1Layout);
        waiting_jPanel1Layout.setHorizontalGroup(
            waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(waiting_jPanel1_jLabel4)
                    .addComponent(waiting_jPanel1_jLabel3)
                    .addComponent(waiting_jPanel1_jLabel2)
                    .addComponent(waiting_jPanel1_jLabel1))
                .addGap(6, 6, 6))
        );

        waiting_jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {waiting_jPanel1_jLabel1, waiting_jPanel1_jLabel2, waiting_jPanel1_jLabel3, waiting_jPanel1_jLabel4});

        waiting_jPanel1Layout.setVerticalGroup(
            waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_jPanel1Layout.createSequentialGroup()
                .addComponent(waiting_jPanel1_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel4))
        );

        waiting_jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {waiting_jPanel1_jLabel1, waiting_jPanel1_jLabel2, waiting_jPanel1_jLabel3, waiting_jPanel1_jLabel4});

        javax.swing.GroupLayout waiting_child_panelLayout = new javax.swing.GroupLayout(waiting_child_panel);
        waiting_child_panel.setLayout(waiting_child_panelLayout);
        waiting_child_panelLayout.setHorizontalGroup(
            waiting_child_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_child_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(992, Short.MAX_VALUE))
        );
        waiting_child_panelLayout.setVerticalGroup(
            waiting_child_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_child_panelLayout.createSequentialGroup()
                .addComponent(waiting_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        waiting_scrollpanel.setViewportView(waiting_child_panel);

        parking_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel1_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel1_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel1_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel1_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-1-48.png"))); // NOI18N

        parking_jPanel1_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel1_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel1Layout = new javax.swing.GroupLayout(parking_jPanel1);
        parking_jPanel1.setLayout(parking_jPanel1Layout);
        parking_jPanel1Layout.setHorizontalGroup(
            parking_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(parking_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parking_jPanel1_jLabel6)
                    .addComponent(parking_jPanel1_jLabel1)
                    .addComponent(parking_jPanel1_jLabel5)
                    .addComponent(parking_jPanel1_jLabel3)
                    .addComponent(parking_jPanel1_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel1_jLabel4))
                .addGap(24, 24, 24))
        );
        parking_jPanel1Layout.setVerticalGroup(
            parking_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel1Layout.createSequentialGroup()
                .addComponent(parking_jPanel1_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel1_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel1_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel1_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel1_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel1_jLabel6)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        parking_jPanel2_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-2-48.png"))); // NOI18N

        parking_jPanel2_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel2_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel2_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel2_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel2_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel2_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel2_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel2Layout = new javax.swing.GroupLayout(parking_jPanel2);
        parking_jPanel2.setLayout(parking_jPanel2Layout);
        parking_jPanel2Layout.setHorizontalGroup(
            parking_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(parking_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel2_jLabel6)
                        .addComponent(parking_jPanel2_jLabel5)
                        .addComponent(parking_jPanel2_jLabel3)
                        .addComponent(parking_jPanel2_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel2_jLabel4))
                    .addComponent(parking_jPanel2_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel2Layout.setVerticalGroup(
            parking_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel2Layout.createSequentialGroup()
                .addComponent(parking_jPanel2_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel2_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel2_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel2_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel2_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel2_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel3_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-3-48.png"))); // NOI18N

        parking_jPanel3_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel3_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel3_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel3_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel3_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel3_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel3_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel3Layout = new javax.swing.GroupLayout(parking_jPanel3);
        parking_jPanel3.setLayout(parking_jPanel3Layout);
        parking_jPanel3Layout.setHorizontalGroup(
            parking_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(parking_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel3_jLabel6)
                        .addComponent(parking_jPanel3_jLabel5)
                        .addComponent(parking_jPanel3_jLabel3)
                        .addComponent(parking_jPanel3_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel3_jLabel4))
                    .addComponent(parking_jPanel3_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel3Layout.setVerticalGroup(
            parking_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel3Layout.createSequentialGroup()
                .addComponent(parking_jPanel3_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel4_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-4-48.png"))); // NOI18N

        parking_jPanel4_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel4_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel4_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel4_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel4_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel4_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel4_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel4Layout = new javax.swing.GroupLayout(parking_jPanel4);
        parking_jPanel4.setLayout(parking_jPanel4Layout);
        parking_jPanel4Layout.setHorizontalGroup(
            parking_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(parking_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parking_jPanel4_jLabel6)
                    .addComponent(parking_jPanel4_jLabel5)
                    .addComponent(parking_jPanel4_jLabel3)
                    .addComponent(parking_jPanel4_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel4_jLabel4)
                    .addComponent(parking_jPanel4_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel4Layout.setVerticalGroup(
            parking_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel4Layout.createSequentialGroup()
                .addComponent(parking_jPanel4_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel5_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-5-48.png"))); // NOI18N

        parking_jPanel5_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel5_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel5_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel5_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel5_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel5_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel5_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel5Layout = new javax.swing.GroupLayout(parking_jPanel5);
        parking_jPanel5.setLayout(parking_jPanel5Layout);
        parking_jPanel5Layout.setHorizontalGroup(
            parking_jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(parking_jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel5_jLabel6)
                        .addComponent(parking_jPanel5_jLabel5)
                        .addComponent(parking_jPanel5_jLabel3)
                        .addComponent(parking_jPanel5_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel5_jLabel4))
                    .addComponent(parking_jPanel5_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel5Layout.setVerticalGroup(
            parking_jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel5Layout.createSequentialGroup()
                .addComponent(parking_jPanel5_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel6_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-6-48.png"))); // NOI18N

        parking_jPanel6_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel6_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel6_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel6_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel6_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel6_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel6_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel6Layout = new javax.swing.GroupLayout(parking_jPanel6);
        parking_jPanel6.setLayout(parking_jPanel6Layout);
        parking_jPanel6Layout.setHorizontalGroup(
            parking_jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(parking_jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel6_jLabel6)
                        .addComponent(parking_jPanel6_jLabel5)
                        .addComponent(parking_jPanel6_jLabel3)
                        .addComponent(parking_jPanel6_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel6_jLabel4))
                    .addComponent(parking_jPanel6_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel6Layout.setVerticalGroup(
            parking_jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel6Layout.createSequentialGroup()
                .addComponent(parking_jPanel6_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel7_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-7-48.png"))); // NOI18N

        parking_jPanel7_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel7_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel7_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel7_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel7_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel7_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel7_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel7Layout = new javax.swing.GroupLayout(parking_jPanel7);
        parking_jPanel7.setLayout(parking_jPanel7Layout);
        parking_jPanel7Layout.setHorizontalGroup(
            parking_jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(parking_jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel7_jLabel6)
                        .addComponent(parking_jPanel7_jLabel5)
                        .addComponent(parking_jPanel7_jLabel3)
                        .addComponent(parking_jPanel7_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel7_jLabel4))
                    .addComponent(parking_jPanel7_jLabel1))
                .addGap(24, 24, 24))
        );
        parking_jPanel7Layout.setVerticalGroup(
            parking_jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel7Layout.createSequentialGroup()
                .addComponent(parking_jPanel7_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel8_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-8-48.png"))); // NOI18N

        parking_jPanel8_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel8_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel8_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel8_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel8_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel8_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel8_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel8Layout = new javax.swing.GroupLayout(parking_jPanel8);
        parking_jPanel8.setLayout(parking_jPanel8Layout);
        parking_jPanel8Layout.setHorizontalGroup(
            parking_jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parking_jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(parking_jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel8_jLabel6)
                        .addComponent(parking_jPanel8_jLabel5)
                        .addComponent(parking_jPanel8_jLabel3)
                        .addComponent(parking_jPanel8_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel8_jLabel4))
                    .addComponent(parking_jPanel8_jLabel1))
                .addGap(24, 24, 24))
        );
        parking_jPanel8Layout.setVerticalGroup(
            parking_jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel8Layout.createSequentialGroup()
                .addComponent(parking_jPanel8_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel9_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-9-48.png"))); // NOI18N

        parking_jPanel9_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel9_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel9_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel9_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel9_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel9_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel9_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel9Layout = new javax.swing.GroupLayout(parking_jPanel9);
        parking_jPanel9.setLayout(parking_jPanel9Layout);
        parking_jPanel9Layout.setHorizontalGroup(
            parking_jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(parking_jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel9_jLabel6)
                        .addComponent(parking_jPanel9_jLabel5)
                        .addComponent(parking_jPanel9_jLabel3)
                        .addComponent(parking_jPanel9_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel9_jLabel4))
                    .addComponent(parking_jPanel9_jLabel1))
                .addGap(25, 25, 25))
        );
        parking_jPanel9Layout.setVerticalGroup(
            parking_jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel9Layout.createSequentialGroup()
                .addComponent(parking_jPanel9_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        parking_jPanel10_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-10-48.png"))); // NOI18N

        parking_jPanel10_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        parking_jPanel10_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N

        parking_jPanel10_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel10_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-garage-48.png"))); // NOI18N

        parking_jPanel10_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parking_jPanel10_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N

        parking_jPanel10_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N

        javax.swing.GroupLayout parking_jPanel10Layout = new javax.swing.GroupLayout(parking_jPanel10);
        parking_jPanel10.setLayout(parking_jPanel10Layout);
        parking_jPanel10Layout.setHorizontalGroup(
            parking_jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(parking_jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parking_jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(parking_jPanel10_jLabel6)
                        .addComponent(parking_jPanel10_jLabel5)
                        .addComponent(parking_jPanel10_jLabel3)
                        .addComponent(parking_jPanel10_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parking_jPanel10_jLabel4))
                    .addComponent(parking_jPanel10_jLabel1))
                .addGap(26, 26, 26))
        );
        parking_jPanel10Layout.setVerticalGroup(
            parking_jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_jPanel10Layout.createSequentialGroup()
                .addComponent(parking_jPanel10_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10_jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10_jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parking_child_panelLayout = new javax.swing.GroupLayout(parking_child_panel);
        parking_child_panel.setLayout(parking_child_panelLayout);
        parking_child_panelLayout.setHorizontalGroup(
            parking_child_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parking_child_panelLayout.createSequentialGroup()
                .addComponent(parking_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parking_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parking_jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parking_child_panelLayout.setVerticalGroup(
            parking_child_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parking_child_panelLayout.createSequentialGroup()
                .addGroup(parking_child_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parking_jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parking_jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        parking_scrollpanel.setViewportView(parking_child_panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parking_scrollpanel))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parking_scrollpanel)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout parking_panelLayout = new javax.swing.GroupLayout(parking_panel);
        parking_panel.setLayout(parking_panelLayout);
        parking_panelLayout.setHorizontalGroup(
            parking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parking_panelLayout.setVerticalGroup(
            parking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(waiting_scrollpanel)
                        .addContainerGap())))
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(parking_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addComponent(action_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parking_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void action_jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_jPanel1MouseClicked
        // TODO add your handling code here:
        AddRecord ar = new AddRecord(this);
        ar.setVisible(true);
    }//GEN-LAST:event_action_jPanel1MouseClicked

    private void action_jPanel2_jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_jPanel2_jLabel1MouseClicked
        // TODO add your handling code here:
        if (w_subpanel_bool) {
            int w_vid_indx = r_vid.indexOf(w_subpanel_vid);
            
            r_vid.remove(w_vid_indx);
            r_type.remove(w_vid_indx);
            r_size.remove(w_vid_indx);
            r_time.remove(w_vid_indx);
            
            JOptionPane.showMessageDialog(this, "Removed ID: "+w_subpanel_vid+"  Total Waiting: "+r_vid.size());
            
            w_subpanel.getParent().remove(w_subpanel);
            w_subpanel_bool = false;
            w_subpanel_vid = -1;
            
            refreshGUI(1);
        }
    }//GEN-LAST:event_action_jPanel2_jLabel1MouseClicked

    private void action_jPanel3_jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_jPanel3_jLabel1MouseClicked
        // TODO add your handling code here:
        startLoop(2);
    }//GEN-LAST:event_action_jPanel3_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
        
        //our program codes go here
    }
    
    private void startLoop(int f) {
       if(f == 1) {
           try {
               while (true) {
                   looper();
                   runList();
                   Thread.sleep(3 * 1000);
               }
           } catch (InterruptedException e) {
               e.printStackTrace();
           }
       }
       else {
           looper();
           runList();
       }
    }
    
    private void refreshGUI(int with_pack) {
        if(with_pack == 1)
            pack();
        
        revalidate();
        repaint();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void runList() {
        int bestIndx = -1;
        int n = r_vid.size();
        int max_size = -1;
        int found_bigger = 0;
        int found_bigger_indx = -1;
        int i = 0;
        
        for (int j = 0; j < 10; j++) {
            if (j == 0) {
                max_size = p_block[j];
            } else if (max_size < p_block[j]) {
                max_size = p_block[j];
            }
        }
        
        if (n > 0) {
            bestIndx = -1;
            
            for (int j = 0; j < 10; j++) {
                Integer rs = new Integer(0);

                if (r_size.get(i) instanceof Integer) {
                    rs = (Integer) r_size.get(i);
                    
                    if((rs > max_size) && (max_size != -1)) {
                        found_bigger = 1;
                        found_bigger_indx = j;
                        break;
                    }
                }

                if ((p_block[j] >= rs) && (p_block_bool[j] == -1)) {
                    if (bestIndx == -1) {
                        bestIndx = j;
                    } else if (p_block[bestIndx] > p_block[j]) {
                        bestIndx = j;
                    }
                }
            }

            if (bestIndx != -1) {
                // 1 sec = 1000 ms
                long curr_time = System.currentTimeMillis();

                //remove the subpanel from GUI
                remove_waitingsGUI(i);
                    
                // allocate block bestIndx to r_vid.get(i) vehicle
                p_block_bool[bestIndx] = 1;

                if (r_vid.get(i) instanceof Integer) {
                    Integer intgr = (Integer) r_vid.get(i);
                    p_vid[bestIndx] = intgr;
                    r_vid.remove(i);
                }

                if (r_type.get(i) instanceof Integer) {
                    Integer intgr = (Integer) r_type.get(i);
                    p_type[bestIndx] = intgr;
                    r_type.remove(i);
                }

                if (r_size.get(i) instanceof Integer) {
                    Integer intgr = (Integer) r_size.get(i);
                    p_size[bestIndx] = intgr;
                    r_size.remove(i);
                }

                if (r_time.get(i) instanceof Integer) {
                    Integer intgr = (Integer) r_time.get(i);
                    p_time[bestIndx] = intgr;
                    p_tlimit[bestIndx] = curr_time + (p_time[bestIndx] * 1000);
                    r_time.remove(i);
                }
                
//                Timer timer = new Timer();
//                timer.schedule(new TimerTask() {
//                    @Override
//                    public void run() {
//                        //This is where we tell it what to do when it hits 5 seconds
//                        looper();
//                        JOptionPane.showMessageDialog(main_panel, "ADDED");
//                    }
//                }, p_time[bestIndx]);
                
                revalidateParking();
            }
            
            if((found_bigger == 1) && (found_bigger_indx > -1)) {
                remove_waitingsGUI(found_bigger_indx);
                r_vid.remove(found_bigger_indx);
                r_type.remove(found_bigger_indx);
                r_size.remove(found_bigger_indx);
                r_time.remove(found_bigger_indx);
                revalidateParking();
            }
        }
    }
    
    private void looper() {
        for(int i = 0; i < 10; i++) {
            if (p_block_bool[i] != -1) {
                if (checkValidity(i) == false) {
                    JOptionPane.showMessageDialog(main_panel, "Parking available at: "+Integer.toString(i+1));
                    p_block_bool[i] = -1;
                    p_vid[i] = 0;
                    p_type[i] = 0;
                    p_size[i] = 0;
                    p_time[i] = 0;
                    p_rmv_notified[i] = 0;
                    revalidateParking();
                }
            }
        }
        
//        revalidateParking();
    }
    
    private void revalidateParking() {
        
        if(p_block_bool[0] == -1) {
            parking_jPanel1_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel1_jLabel3.setText("");
            parking_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel1_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel1_jLabel5.setText("");
            parking_jPanel1_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel1_jLabel6.setText("");
        }
        else {
            parking_jPanel1_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel1_jLabel3.setText(Integer.toString(p_vid[0]));
            
            if(p_type[0] == 1)
                parking_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[0] == 2)
                parking_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel1_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel1_jLabel5.setText(Integer.toString(p_size[0]));
            parking_jPanel1_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel1_jLabel6.setText(Integer.toString(p_time[0]));
        }
        
        if(p_block_bool[1] == -1) {
            parking_jPanel2_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel2_jLabel3.setText("");
            parking_jPanel2_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel2_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel2_jLabel5.setText("");
            parking_jPanel2_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel2_jLabel6.setText("");
        }
        else {
            parking_jPanel2_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel2_jLabel3.setText(Integer.toString(p_vid[1]));
            
            if(p_type[1] == 1)
                parking_jPanel2_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[1] == 2)
                parking_jPanel2_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel2_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel2_jLabel5.setText(Integer.toString(p_size[1]));
            parking_jPanel2_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel2_jLabel6.setText(Integer.toString(p_time[1]));
        }
        
        if(p_block_bool[2] == -1) {
            parking_jPanel3_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel3_jLabel3.setText("");
            parking_jPanel3_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel3_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel3_jLabel5.setText("");
            parking_jPanel3_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel3_jLabel6.setText("");
        }
        else {
            parking_jPanel3_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel3_jLabel3.setText(Integer.toString(p_vid[2]));
            
            if(p_type[2] == 1)
                parking_jPanel3_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[2] == 2)
                parking_jPanel3_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel3_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel3_jLabel5.setText(Integer.toString(p_size[2]));
            parking_jPanel3_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel3_jLabel6.setText(Integer.toString(p_time[2]));
        }
        
        if(p_block_bool[3] == -1) {
            parking_jPanel4_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel4_jLabel3.setText("");
            parking_jPanel4_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel4_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel4_jLabel5.setText("");
            parking_jPanel4_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel4_jLabel6.setText("");
        }
        else {
            parking_jPanel4_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel4_jLabel3.setText(Integer.toString(p_vid[3]));
            
            if(p_type[3] == 1)
                parking_jPanel4_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[3] == 2)
                parking_jPanel4_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel4_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel4_jLabel5.setText(Integer.toString(p_size[3]));
            parking_jPanel4_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel4_jLabel6.setText(Integer.toString(p_time[3]));
        }
        
        if(p_block_bool[4] == -1) {
            parking_jPanel5_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel5_jLabel3.setText("");
            parking_jPanel5_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel5_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel5_jLabel5.setText("");
            parking_jPanel5_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel5_jLabel6.setText("");
        }
        else {
            parking_jPanel5_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel5_jLabel3.setText(Integer.toString(p_vid[4]));
            
            if(p_type[4] == 1)
                parking_jPanel5_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[4] == 2)
                parking_jPanel5_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel5_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel5_jLabel5.setText(Integer.toString(p_size[4]));
            parking_jPanel5_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel5_jLabel6.setText(Integer.toString(p_time[4]));
        }
        
        if(p_block_bool[5] == -1) {
            parking_jPanel6_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel6_jLabel3.setText("");
            parking_jPanel6_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel6_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel6_jLabel5.setText("");
            parking_jPanel6_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel6_jLabel6.setText("");
        }
        else {
            parking_jPanel6_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel6_jLabel3.setText(Integer.toString(p_vid[5]));
            
            if(p_type[5] == 1)
                parking_jPanel6_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[5] == 2)
                parking_jPanel6_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel6_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel6_jLabel5.setText(Integer.toString(p_size[5]));
            parking_jPanel6_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel6_jLabel6.setText(Integer.toString(p_time[5]));
        }
        
        if(p_block_bool[6] == -1) {
            parking_jPanel7_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel7_jLabel3.setText("");
            parking_jPanel7_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel7_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel7_jLabel5.setText("");
            parking_jPanel7_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel7_jLabel6.setText("");
        }
        else {
            parking_jPanel7_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel7_jLabel3.setText(Integer.toString(p_vid[6]));
            
            if(p_type[6] == 1)
                parking_jPanel7_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[6] == 2)
                parking_jPanel7_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel7_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel7_jLabel5.setText(Integer.toString(p_size[6]));
            parking_jPanel7_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel7_jLabel6.setText(Integer.toString(p_time[6]));
        }
        
        if(p_block_bool[7] == -1) {
            parking_jPanel8_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel8_jLabel3.setText("");
            parking_jPanel8_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel8_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel8_jLabel5.setText("");
            parking_jPanel8_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel8_jLabel6.setText("");
        }
        else {
            parking_jPanel8_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel8_jLabel3.setText(Integer.toString(p_vid[7]));
            
            if(p_type[7] == 1)
                parking_jPanel8_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[7] == 2)
                parking_jPanel8_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel8_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel8_jLabel5.setText(Integer.toString(p_size[7]));
            parking_jPanel8_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel8_jLabel6.setText(Integer.toString(p_time[7]));
        }
        
        if(p_block_bool[8] == -1) {
            parking_jPanel9_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel9_jLabel3.setText("");
            parking_jPanel9_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel9_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel9_jLabel5.setText("");
            parking_jPanel9_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel9_jLabel6.setText("");
        }
        else {
            parking_jPanel9_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel9_jLabel3.setText(Integer.toString(p_vid[8]));
            
            if(p_type[8] == 1)
                parking_jPanel9_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[8] == 2)
                parking_jPanel9_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel9_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel9_jLabel5.setText(Integer.toString(p_size[8]));
            parking_jPanel9_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel9_jLabel6.setText(Integer.toString(p_time[8]));
        }
        
        if(p_block_bool[9] == -1) {
            parking_jPanel10_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-numbers-48.png"))); // NOI18N
            parking_jPanel10_jLabel3.setText("");
            parking_jPanel10_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N
            parking_jPanel10_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-add-white-space-48.png"))); // NOI18N
            parking_jPanel10_jLabel5.setText("");
            parking_jPanel10_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-watch-48.png"))); // NOI18N
            parking_jPanel10_jLabel6.setText("");
        }
        else {
            parking_jPanel10_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel10_jLabel3.setText(Integer.toString(p_vid[9]));
            
            if(p_type[9] == 1)
                parking_jPanel10_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
            else if(p_type[9] == 2)
                parking_jPanel10_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
            
            parking_jPanel10_jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel10_jLabel5.setText(Integer.toString(p_size[9]));
            parking_jPanel10_jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
            parking_jPanel10_jLabel6.setText(Integer.toString(p_time[9]));
        }
        
        refreshGUI(1);
    }

    public void addRecord(int vid, int type, int size, int time) {
        r_vid.add(vid);
        r_type.add(type);
        r_size.add(size);
        r_time.add(time);
        
        waiting_child_panel.setLayout(new java.awt.FlowLayout());
        Waiting_SubPanel waiting_subpanel = new Waiting_SubPanel(vid, type, size, time);
        waiting_child_panel.add(waiting_subpanel);
        waiting_subpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                waiting_subpanel_MouseClicked(waiting_subpanel, evt);
            }
        });
        
        refreshGUI(0);
    }
    
    // return the size of r_vid/r_size/r_type/r_time
    public int get_r_length() {
        return r_vid.size();
    }
    
    private void waiting_subpanel_MouseClicked(javax.swing.JPanel subpanel, java.awt.event.MouseEvent evt) {
        w_subpanel = subpanel;
        w_subpanel_bool = true;
        int vid = get_vid(subpanel);
        w_subpanel_vid = vid;
        
        JOptionPane.showMessageDialog(this, "Selected Vehicle ID: "+vid+"  Total Waiting: "+r_vid.size());
    }
    
    private int get_vid(javax.swing.JPanel subpanel) {
        int rtn = -1;
        
        java.awt.Component[] comps_outer = subpanel.getComponents();
        if (comps_outer[comps_outer.length-1] instanceof javax.swing.JPanel) {
            javax.swing.JPanel pnl = (javax.swing.JPanel) comps_outer[comps_outer.length-1];
            java.awt.Component[] comps = pnl.getComponents();
            if (comps[comps.length-1] instanceof javax.swing.JLabel) {
                javax.swing.JLabel lbl = (javax.swing.JLabel) comps[comps.length-1];
                rtn = Integer.parseInt(lbl.getText());
            }
        }
        
        return rtn;
    }
    
    private void remove_waitingsGUI(int vid) {
        javax.swing.JPanel panel = this.waiting_child_panel;
        java.awt.Component[] comps_panel = panel.getComponents();
        
        for(java.awt.Component comp_panel : comps_panel)
        {
            if (comp_panel instanceof javax.swing.JPanel) {
                javax.swing.JPanel subpanel = (javax.swing.JPanel) comp_panel;
                java.awt.Component[] comps_subpanel = subpanel.getComponents();
                
                if (comps_subpanel[comps_subpanel.length - 1] instanceof javax.swing.JPanel) {
                    javax.swing.JPanel subpanel_2 = (javax.swing.JPanel) comps_subpanel[comps_subpanel.length - 1];
                    java.awt.Component[] comps_subpanel_2 = subpanel_2.getComponents();
                    
                    if (comps_subpanel_2[comps_subpanel_2.length - 1] instanceof javax.swing.JLabel) {
                        javax.swing.JLabel lbl = (javax.swing.JLabel) comps_subpanel_2[comps_subpanel_2.length - 1];
                        int rtn = Integer.parseInt(lbl.getText());

                        if (rtn == Integer.parseInt(r_vid.get(vid).toString())) {
                            subpanel.getParent().remove(subpanel);
                            break;
                        }
                    }
                }
            }
        }
    }
    
    private int nextVehicleToPark() {
        int rtn = -1; //returns the index number of the next vehicle to be parked
        
        int n = r_vid.size();
        int max_size = -1;
        
        if (n > 0) {
            int j;
            
            for (j = 0; j < 10; j++) {
                if (j == 0) {
                    max_size = p_block[j];
                } else if (max_size < p_block[j]) {
                    max_size = p_block[j];
                }
            }
            
            for (j=0; j < n; j++) {
                if(Integer.parseInt(r_size.get(j).toString()) <= max_size) {
                    rtn = j;
                    break;
                }
            }
        }
        
        return rtn;
    }
    
    private boolean checkValidity(int indx) {
        long curr_time = System.currentTimeMillis();
        
        if (p_tlimit[indx] < curr_time) {
            return false;
        }
        else {
            long diff = p_tlimit[indx] - curr_time;
            if((diff <= RMV_NOTIFY_TIME) && (p_rmv_notified[indx] == 0)) {
                p_rmv_notified[indx] = 1;
                
                int nextVidIndx = nextVehicleToPark();
                if(nextVidIndx != -1) {
                    int nextVid = Integer.parseInt(r_vid.get(nextVidIndx).toString());
                    JOptionPane.showMessageDialog(parking_panel, "Next Parking at "+(indx+1)+" (within "+(RMV_NOTIFY_TIME/1000)+" second)  Vehicle ID: "+nextVid+".", "CarParko", JOptionPane.INFORMATION_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(parking_panel, "Parking will be available at "+(indx+1)+" within "+(RMV_NOTIFY_TIME/1000)+" second.", "CarParko", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            return true;
        }
    }
    
    public ArrayList get_r_vid() {
        return r_vid;
    }
    
    private void initParking() {
        parking_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel1_jLabel2.setText(Integer.toString(p_block[0]));
        
        parking_jPanel2_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel2_jLabel2.setText(Integer.toString(p_block[1]));
        
        parking_jPanel3_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel3_jLabel2.setText(Integer.toString(p_block[2]));
        
        parking_jPanel4_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel4_jLabel2.setText(Integer.toString(p_block[3]));
        
        parking_jPanel5_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel5_jLabel2.setText(Integer.toString(p_block[4]));
        
        parking_jPanel6_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel6_jLabel2.setText(Integer.toString(p_block[5]));
        
        parking_jPanel7_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel7_jLabel2.setText(Integer.toString(p_block[6]));
        
        parking_jPanel8_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel8_jLabel2.setText(Integer.toString(p_block[7]));
        
        parking_jPanel9_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel9_jLabel2.setText(Integer.toString(p_block[8]));
        
        parking_jPanel10_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        parking_jPanel10_jLabel2.setText(Integer.toString(p_block[9]));
        
        refreshGUI(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action_jPanel1;
    private javax.swing.JLabel action_jPanel1_jLabel1;
    private javax.swing.JPanel action_jPanel2;
    private javax.swing.JLabel action_jPanel2_jLabel1;
    private javax.swing.JPanel action_jPanel3;
    private javax.swing.JLabel action_jPanel3_jLabel1;
    private javax.swing.JPanel action_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel parking_child_panel;
    private javax.swing.JPanel parking_jPanel1;
    private javax.swing.JPanel parking_jPanel10;
    private javax.swing.JLabel parking_jPanel10_jLabel1;
    private javax.swing.JLabel parking_jPanel10_jLabel2;
    private javax.swing.JLabel parking_jPanel10_jLabel3;
    private javax.swing.JLabel parking_jPanel10_jLabel4;
    private javax.swing.JLabel parking_jPanel10_jLabel5;
    private javax.swing.JLabel parking_jPanel10_jLabel6;
    private javax.swing.JLabel parking_jPanel1_jLabel1;
    private javax.swing.JLabel parking_jPanel1_jLabel2;
    private javax.swing.JLabel parking_jPanel1_jLabel3;
    private javax.swing.JLabel parking_jPanel1_jLabel4;
    private javax.swing.JLabel parking_jPanel1_jLabel5;
    private javax.swing.JLabel parking_jPanel1_jLabel6;
    private javax.swing.JPanel parking_jPanel2;
    private javax.swing.JLabel parking_jPanel2_jLabel1;
    private javax.swing.JLabel parking_jPanel2_jLabel2;
    private javax.swing.JLabel parking_jPanel2_jLabel3;
    private javax.swing.JLabel parking_jPanel2_jLabel4;
    private javax.swing.JLabel parking_jPanel2_jLabel5;
    private javax.swing.JLabel parking_jPanel2_jLabel6;
    private javax.swing.JPanel parking_jPanel3;
    private javax.swing.JLabel parking_jPanel3_jLabel1;
    private javax.swing.JLabel parking_jPanel3_jLabel2;
    private javax.swing.JLabel parking_jPanel3_jLabel3;
    private javax.swing.JLabel parking_jPanel3_jLabel4;
    private javax.swing.JLabel parking_jPanel3_jLabel5;
    private javax.swing.JLabel parking_jPanel3_jLabel6;
    private javax.swing.JPanel parking_jPanel4;
    private javax.swing.JLabel parking_jPanel4_jLabel1;
    private javax.swing.JLabel parking_jPanel4_jLabel2;
    private javax.swing.JLabel parking_jPanel4_jLabel3;
    private javax.swing.JLabel parking_jPanel4_jLabel4;
    private javax.swing.JLabel parking_jPanel4_jLabel5;
    private javax.swing.JLabel parking_jPanel4_jLabel6;
    private javax.swing.JPanel parking_jPanel5;
    private javax.swing.JLabel parking_jPanel5_jLabel1;
    private javax.swing.JLabel parking_jPanel5_jLabel2;
    private javax.swing.JLabel parking_jPanel5_jLabel3;
    private javax.swing.JLabel parking_jPanel5_jLabel4;
    private javax.swing.JLabel parking_jPanel5_jLabel5;
    private javax.swing.JLabel parking_jPanel5_jLabel6;
    private javax.swing.JPanel parking_jPanel6;
    private javax.swing.JLabel parking_jPanel6_jLabel1;
    private javax.swing.JLabel parking_jPanel6_jLabel2;
    private javax.swing.JLabel parking_jPanel6_jLabel3;
    private javax.swing.JLabel parking_jPanel6_jLabel4;
    private javax.swing.JLabel parking_jPanel6_jLabel5;
    private javax.swing.JLabel parking_jPanel6_jLabel6;
    private javax.swing.JPanel parking_jPanel7;
    private javax.swing.JLabel parking_jPanel7_jLabel1;
    private javax.swing.JLabel parking_jPanel7_jLabel2;
    private javax.swing.JLabel parking_jPanel7_jLabel3;
    private javax.swing.JLabel parking_jPanel7_jLabel4;
    private javax.swing.JLabel parking_jPanel7_jLabel5;
    private javax.swing.JLabel parking_jPanel7_jLabel6;
    private javax.swing.JPanel parking_jPanel8;
    private javax.swing.JLabel parking_jPanel8_jLabel1;
    private javax.swing.JLabel parking_jPanel8_jLabel2;
    private javax.swing.JLabel parking_jPanel8_jLabel3;
    private javax.swing.JLabel parking_jPanel8_jLabel4;
    private javax.swing.JLabel parking_jPanel8_jLabel5;
    private javax.swing.JLabel parking_jPanel8_jLabel6;
    private javax.swing.JPanel parking_jPanel9;
    private javax.swing.JLabel parking_jPanel9_jLabel1;
    private javax.swing.JLabel parking_jPanel9_jLabel2;
    private javax.swing.JLabel parking_jPanel9_jLabel3;
    private javax.swing.JLabel parking_jPanel9_jLabel4;
    private javax.swing.JLabel parking_jPanel9_jLabel5;
    private javax.swing.JLabel parking_jPanel9_jLabel6;
    private javax.swing.JPanel parking_panel;
    private javax.swing.JScrollPane parking_scrollpanel;
    private javax.swing.JPanel waiting_child_panel;
    private javax.swing.JPanel waiting_jPanel1;
    private javax.swing.JLabel waiting_jPanel1_jLabel1;
    private javax.swing.JLabel waiting_jPanel1_jLabel2;
    private javax.swing.JLabel waiting_jPanel1_jLabel3;
    private javax.swing.JLabel waiting_jPanel1_jLabel4;
    private javax.swing.JScrollPane waiting_scrollpanel;
    // End of variables declaration//GEN-END:variables
}
