/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carparko;

/**
 *
 * @author nilay
 */
public class Waiting_SubPanel extends javax.swing.JPanel {

    Waiting_SubPanel sp;
    int vid, type, size, time;
    
    /**
     * Creates new form Waiting_SubPanel
     * @param vid
     * @param type
     * @param size
     * @param time
     */
    public Waiting_SubPanel(int vid, int type, int size, int time) {
        initComponents();
        sp = this;
        this.vid = vid;
        this.type = type;
        this.size = size;
        this.time = time;
        waiting_jPanel1_jLabel1.setText(Integer.toString(this.vid));
        
        if(this.type == 1) {
            waiting_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-fiat-500-48.png"))); // NOI18N
        }
        else if(this.type == 2) {
            waiting_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-container-truck-48.png"))); // NOI18N
        }
        else {
            //no change
        }
        
        waiting_jPanel1_jLabel3.setText(Integer.toString(this.size));
        waiting_jPanel1_jLabel4.setText(Integer.toString(this.time));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waiting_jPanel1 = new javax.swing.JPanel();
        waiting_jPanel1_jLabel1 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel2 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel3 = new javax.swing.JLabel();
        waiting_jPanel1_jLabel4 = new javax.swing.JLabel();

        waiting_jPanel1_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waiting_jPanel1_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N
        waiting_jPanel1_jLabel1.setMaximumSize(new java.awt.Dimension(48, 48));
        waiting_jPanel1_jLabel1.setMinimumSize(new java.awt.Dimension(48, 48));
        waiting_jPanel1_jLabel1.setPreferredSize(new java.awt.Dimension(48, 48));

        waiting_jPanel1_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waiting_jPanel1_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-traffic-jam-48.png"))); // NOI18N

        waiting_jPanel1_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waiting_jPanel1_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N

        waiting_jPanel1_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waiting_jPanel1_jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carparko/assests/icons-blank-48.png"))); // NOI18N

        javax.swing.GroupLayout waiting_jPanel1Layout = new javax.swing.GroupLayout(waiting_jPanel1);
        waiting_jPanel1.setLayout(waiting_jPanel1Layout);
        waiting_jPanel1Layout.setHorizontalGroup(
            waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(waiting_jPanel1_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waiting_jPanel1_jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waiting_jPanel1_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waiting_jPanel1_jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        waiting_jPanel1Layout.setVerticalGroup(
            waiting_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiting_jPanel1Layout.createSequentialGroup()
                .addComponent(waiting_jPanel1_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting_jPanel1_jLabel4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waiting_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel waiting_jPanel1;
    private javax.swing.JLabel waiting_jPanel1_jLabel1;
    private javax.swing.JLabel waiting_jPanel1_jLabel2;
    private javax.swing.JLabel waiting_jPanel1_jLabel3;
    private javax.swing.JLabel waiting_jPanel1_jLabel4;
    // End of variables declaration//GEN-END:variables
}
